version: "3"

services:
 app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - app.env
    depends_on:
      - db
 db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - db.env
