version: "3"

services:
 db:
    image: postgres
    container_name: lifelog_db
    env_file: db.env
 app:
    build: .
    image: lifelog/app
    container_name: lifelog_app
    ports:
      - 8080:8080
    env_file:
      - app.env
    depends_on:
      - db
